name: pip-download

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'The package to DL'
        required: true
      pyversion:
        description: 'Python version'
        required: true
        default: '3.11'
        type: choice
        options:
          - "3.10"
          - "3.11"
          - "3.12"

jobs:
  download:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: WF for ${{ inputs.package }}
        run: |
          echo "DL: $PACKAGE"
        env:
          PACKAGE: ${{ inputs.package }}

      - name: Set up Python ${{ inputs.pyversion }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.pyversion }}

      - name: Install python requirements
        run: |
          pip install pip wheel -U

      - name: Download ${{ inputs.package }}
        env:
          PACKAGE: ${{ inputs.package }}
        run: |
          mkdir -p dependencies
          cd dependencies
          pip download $PACKAGE

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.package }}.downloads.zip
          files: |
            dependencies/*