name: pip-download

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'The package to DL'
        required: true
      pyversion:
        description: 'Python version'
        required: true
        default: '3.11'
        type: choice
        options:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

jobs:
  download:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: WF for ${{ inputs.package }}
        run: |
          echo "DL: $PACKAGE"
        env:
          PACKAGE: ${{ inputs.package }}

      - name: Set up Python ${{ inputs.pyversion }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.pyversion }}

      - name: Install python requirements
        run: |
          pip install pip wheel pkginfo -U

      - name: Download ${{ inputs.package }}
        id: download
        env:
          PACKAGE: ${{ inputs.package }}
          PYVERSION: ${{ inputs.pyversion }}
        run: |
          mkdir -p dependencies
          cd dependencies
          pip download $PACKAGE > out
          cat out
          WHEEL_NAME=$(head -n 2 out | tail -n 1 | grep "Downloading" | cut -f4 -d' ' | sed 's/.metadata//')
          pkginfo -f version $WHEEL_NAME | cut -f2 -d' '
          PKG_VERSION=$(pkginfo -f version $WHEEL_NAME | cut -f2 -d' ')
          echo "pkg_version=${PKG_VERSION}" >> "$GITHUB_OUTPUT"
          zip -r $PACKAGE.v$PKG_VERSION.py$PYVERSION.zip *
          rm out
          date >> package_list.txt
          echo "\`\`\`" >> package_list.txt
          ls -1 | grep -v ".zip" | grep -v package_list >> package_list.txt
          echo "\`\`\`" >> package_list.txt

          cat package_list.txt

          split -d -b 500MB $PACKAGE.v$PKG_VERSION.py$PYVERSION.zip $PACKAGE.v$PKG_VERSION.py$PYVERSION.zip-part-

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.package }}.v${{ steps.download.outputs.pkg_version }}.py${{ inputs.pyversion }}
          make_latest: true
          body_path: dependencies/package_list.txt
          files: |
            dependencies/${{ inputs.package }}.v${{ steps.download.outputs.pkg_version }}.py${{ inputs.pyversion }}.zip-part*
